### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by SurajKande** [iamaziz/etl#1]
Data Pipeline created
         extracting data from source ....
         formatting and transforming data ...
Traceback (most recent call last):
  File "pipeline.py", line 105, in <module>
    pipeline.transform()
  File "pipeline.py", line 46, in transform
    unemployment = self.unemployment[unemp_idx + unemp_cols].copy()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\indexing.py", line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['State' 'Area_name'] not in index"

**Comment by iamaziz** [comment]
@SurajKande thanks for reporting this, please try again it should work now :]
